# Generated by Django 2.2.2 on 2019-06-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
