# Generated by Django 2.2.2 on 2019-06-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch', '0003_auto_20190627_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='efficiency',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
